### ISSUE TITLE
Migrating android plugin to use io.flutter.embedding instead of io.flutter

### ISSUE THREAD

**Issue by elias8** [ppicas/flutter-android-background#3]
The code works well on flutter 1.12 and older but since flutter is migrating android plugins to use io.flutter.embedding as mentioned [here](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects) is there a way to achieve the same result in the newer version. 

I have changed the code inside the activity to the new version. But the problem is with the registrant in the [BackgroundService](https://github.com/ppicas/flutter-android-background/blob/master/android/app/src/main/kotlin/com/example/background/BackgroundService.kt) `GeneratedPluginRegistrant.registerWith(pluginRegistry)` because the newer version requires a flutter engine instead of plugin registry (`GeneratedPluginRegistrant.registerWith(flutterEngine)`).

Thanks.

**Comment by ppicas** [comment]
Hi Elias, yeah I'm aware of the changes that Flutter 1.12 brought. It was funny because this repo was released at same time as the new Flutter version.

I'm planning to investigate new solutions to run apps in the background using new APIs introduced in Flutter 1.12 SDK. For instance the use of [FlutterEngineCache](https://api.flutter.dev/javadoc/io/flutter/embedding/engine/FlutterEngineCache.html) looks very promising

**Comment by 1legality** [comment]
Hi, any news on this issue? Thanks!

**Comment by rakeshchevuru** [comment]
Hi!! Do you have any update on this issue? Thanks!!

**Comment by fried19** [comment]
I have the same error.How can I fix it please

**Comment by pitazzo** [comment]
Hey there! I'm also looking for a way to port this great project to the current FLutter's version

**Comment by ppicas** [comment]
Hi everybody! I updated the repo making the project compatible with v2. This should solve your problem :)
