### ISSUE TITLE
How to stop this service ?

### ISSUE THREAD

**Issue by SohanRoni** [ppicas/flutter-android-background#4]
the service is running very well in background but there is no way to stop it when i need , can you kindly help ?

**Comment by ndphuong** [comment]
Just uninstall it

**Comment by ppicas** [comment]
@ndphuong  is right, the provided example does not provide a way to stop the service. You have to **uninstall the app** or **force the process to stop** by using system app settings.

I did the example in this way in order to make it simple enough. But the example can easily extended in order to support stop the background service. For instance you could add another method in the MethodChannel called "stopService" that calls a new method called BackgroundService.stopService() that stops the background service. The place to add this new method in the MethodChannel is here: https://github.com/ppicas/flutter-android-background/blob/master/android/app/src/main/kotlin/com/example/background/MainActivity.kt#L15.

**Comment by ExypnosDevloper** [comment]
> Just uninstall it

Force stop

**Comment by torian257x** [comment]
I am thankful for this project

I can understand to create a method BackgroundService.stopService()

what I don't understand is how to actually properly stop it. Coming from a none-android background, this isn't obvious (nor is it obvious where to start looking).

I guess google?  I found this:

https://stackoverflow.com/questions/20857120/what-is-the-proper-way-to-stop-a-service-running-as-foreground

**Comment by torian257x** [comment]
I forked and added a floating button to start / stop the service. It's a bit messy, but it seems to work and should get everyone going in the right direction who has the same question:
https://github.com/Jossnaz/flutter-android-background
